
spring:
  application:
    name: saas-platform
  
  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
    show-sql: false
    defer-datasource-initialization: true
    h2:
      console:
        enabled: true
        path: /h2-console
  
  flyway:
    enabled: false
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  camunda:
    bpm:
      auto-deployment-enabled: false
      database:
        schema-update: false
      job-execution:
        deployment-aware: false
  
  quartz:
    job-store-type: memory
    auto-startup: false

server:
  port: ${SERVER_PORT:8090}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
  health:
    defaults:
      enabled: false
    camunda:
      enabled: false

jwt:
  secret: ${JWT_SECRET:ZmQ0ZGI5NjQ0NDQxNGFmN2U5MjhkODNmODFmYjBjMjQ4NzIxZmQ0ZGI5NjQ0NDQxNGFmN2U5MjhkODNmODFmYjBjMjQ4NzIx}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:19006}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
  
  tenant:
    resolution:
      header: X-Tenant-ID
      subdomain: true
  
  integrations:
    stripe:
      secret-key: ${STRIPE_SECRET_KEY:}
      webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
    twilio:
      account-sid: ${TWILIO_ACCOUNT_SID:}
      auth-token: ${TWILIO_AUTH_TOKEN:}
    sendgrid:
      api-key: ${SENDGRID_API_KEY:}
    firebase:
      project-id: ${FIREBASE_PROJECT_ID:}
      private-key-id: ${FIREBASE_PRIVATE_KEY_ID:}
      private-key: ${FIREBASE_PRIVATE_KEY:}
      client-email: ${FIREBASE_CLIENT_EMAIL:}

logging:
  level:
    com.saasplatform: DEBUG
    org.springframework.security: DEBUG
    org.camunda.bpm: INFO
    org.quartz: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

